### ISSUE TITLE
Copyright appears to be wrong - please check the license

### ISSUE THREAD

**Issue by fossfreedom** [ubuntucinnamonremix/kimmo-icon-theme#1]
I doubt that this is correct:

 2013 Satyajit Sahoo <satyajit.happy@gmail.com>
 2016-2017, horst3180 <email address hidden>
 2017-2019, Nicohood <mail@nicohood.de> and David Mohammed <fossfreedom@ubuntu.com>
 2019 Joshua Peisach <ubuntucinnamonremix7@gmail.com>

The copyright authors should reflect those that had contributed any part of the project including those authors that the icon theme is based on (if any).

If the icon-theme is based on another icon-theme then the license should reflect that - you cannot (in most cases) just change the license to another license.

**Comment by ubuntucinnamonremix** [comment]
Solved.
